### ISSUE TITLE
DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by dimitriharding** [veniversum/air-routes-vis#2]
Was hoping to get a glimpse but.... 
<img width="1657" alt="screen shot 2018-04-19 at 6 56 04 pm" src="https://user-images.githubusercontent.com/12203794/39026731-748da432-4403-11e8-87da-5b1e05bc526a.png">
 http://thisissky.net

**Comment by veniversum** [comment]
@dimitriharding Oops, the domain name expired. I've moved it over to here for now:
https://skynet.veniversum.me/
